// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBnjAyMN8Mk9O3RTmFWv3LCmfQzagSX1o',
    appId: '1:753785125549:web:6cd0f128811a7a36a46424',
    messagingSenderId: '753785125549',
    projectId: 'kayla-testapp',
    authDomain: 'kayla-testapp.firebaseapp.com',
    storageBucket: 'kayla-testapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkGdxYXRpOI58OYgGZ3oa9rx2_6ykFk00',
    appId: '1:753785125549:android:225873a3e9574ba2a46424',
    messagingSenderId: '753785125549',
    projectId: 'kayla-testapp',
    storageBucket: 'kayla-testapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNT3KrgRymFguHBRm_ts1Wd81lbpGPgaU',
    appId: '1:753785125549:ios:40dd2142bd34f4f9a46424',
    messagingSenderId: '753785125549',
    projectId: 'kayla-testapp',
    storageBucket: 'kayla-testapp.appspot.com',
    iosClientId: '753785125549-pk7jhfesblubnslmoh3vm3ab62lfleon.apps.googleusercontent.com',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNT3KrgRymFguHBRm_ts1Wd81lbpGPgaU',
    appId: '1:753785125549:ios:40dd2142bd34f4f9a46424',
    messagingSenderId: '753785125549',
    projectId: 'kayla-testapp',
    storageBucket: 'kayla-testapp.appspot.com',
    iosClientId: '753785125549-pk7jhfesblubnslmoh3vm3ab62lfleon.apps.googleusercontent.com',
    iosBundleId: 'com.example.testapp',
  );
}
